name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Upload project files to AWS (skip build here)
      - name: Upload files to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          ARGS: "-avz --delete"
          # Upload everything needed to build/run
          SOURCE: "src package.json package-lock.json public next.config.js"
          REMOTE_HOST: ${{ secrets.AWS_HOST }}
          REMOTE_USER: ubuntu
          TARGET: "~/apps/nextjs-app"

      # 3. Install & Build on server + Restart PM2
      - name: Build & Restart on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd ~/apps/nextjs-app
            npm install --omit=dev
            npm run build
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
