name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd ~/apps/nextjs-app || git clone https://github.com/your-username/your-repo.git ~/apps/nextjs-app
            cd ~/apps/nextjs-app
            git fetch --all
            git reset --hard origin/main
            npm install --omit=dev
            npm run build
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
