name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install deps and build
      - name: Install dependencies
        run: npm install
      - name: Build Next.js app
        run: npm run build

      # 4. Upload build + needed files to AWS
      - name: Upload files to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          ARGS: "-avz --delete"
          SOURCE: ".next package.json package-lock.json public next.config.js"
          REMOTE_HOST: ${{ secrets.AWS_HOST }}
          REMOTE_USER: ubuntu
          TARGET: "~/apps/nextjs-app"

      # 5. Restart app with PM2
      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd ~/apps/nextjs-app
            npm install --omit=dev
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
